### ISSUE TITLE
Question: How to register new express routes for the built in express server

### ISSUE THREAD

**Issue by Chris2011** [OfficeDev/Office-Addin-TaskPane-SSO-JS#29]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

Please describe the behavior you were expecting
I can import the express router from the application somehow and add new routes to it that my application can call them.

# Current behavior

Please provide information about the failure. What is the current behavior? If it is not a bug, please add it to [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/164751-office-developer-tools), so that it gets added to our feature roadmap.

We want to add new routes to the internal express server of the office-addin-sso lib. We need to do it to play with outlook token and send it to our own services. For this we need to add new routes to the express server of the application that started via npm start. This seems not possible. So the question is, is it possible to register new routes to your built in express server?

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Not a bug, so no steps to reproduce.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Node version: 14.16.0
* Office version: Office 365
* Tool version: "office-addin-sso": "^1.0.36"

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by mattgeim** [comment]
@millerds  can you take a look at this?

**Comment by Chris2011** [comment]
Great thx :)
