### ISSUE TITLE
Excel Addin OfficeJs SSO authentication working in Web not working in Excel desktop

### ISSUE THREAD

**Issue by Sachin2-u** [OfficeDev/Office-Addin-TaskPane-SSO-JS#49]
Excel desktop SSO issue

****************************
- [Yes ] I am running the latest version of Node and the tools
- [Yes] I checked the documentation and found no answer
- [Yes ] I checked to make sure that this issue has not already been filed

npm packages installed
+-- @azure/msal-browser@2.22.1
+-- @babel/core@7.13.14
+-- @babel/preset-env@7.13.12
+-- @babel/preset-typescript@7.13.0
+-- @types/office-js@1.0.181
+-- @types/office-runtime@1.0.17
+-- acorn@8.5.0
+-- babel-loader@8.2.2
+-- copy-webpack-plugin@9.0.1
+-- core-js@3.9.1
+-- eslint-plugin-office-addins@2.0.0
+-- file-loader@6.2.0
+-- html-loader@2.1.2
+-- html-webpack-plugin@5.3.2
+-- msal@1.4.16
+-- office-addin-cli@1.3.5
+-- office-addin-debugging@4.3.8
+-- office-addin-dev-certs@1.7.7
+-- office-addin-lint@2.0.0
+-- office-addin-manifest@1.7.7
+-- office-addin-prettier-config@1.1.4
+-- os-browserify@0.3.0
+-- polyfills@2.1.1
+-- process@0.11.10
+-- regenerator-runtime@0.13.7
+-- source-map-loader@3.0.0
+-- ts-loader@9.2.5
+-- typescript@4.4.3
+-- webpack-cli@4.8.0
+-- webpack-dev-server@4.7.3
`-- webpack@5.53.0

# Expected behavior
When using this line for login => let bootstrapToken = await OfficeRuntime.auth.getAccessToken({ allowSignInPrompt: true });

It should authenticate the user 

# Current behavior
While Authentication on login click its  throwing error in desktop excel  

Error: Message received in processMessage: {"type":"dialogMessageReceived","message":"{\"status\":\"failure\",\"result\":{\"errorCode\":\"user_login_error\",\"errorMessage\":\"User login is required. For silent calls, request must contain either sid or login_hint\",\"name\":\"ClientAuthError\"}}","origin":"https://localhost:4200"}

Its working fine in Web Excel with the same code

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. start the app through npm start 
2. Click on Login button
3. pop up blinks and throws error
4. To see error  open Edge dev tools and select addin as target
![image](https://user-images.githubusercontent.com/101329571/157654719-24175d48-55f2-435e-bad8-94d1b0f56904.png)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows
* Node version: v16.14.0
* Office version: 2016
* Tool version: msal 1.4.16

## Failure Logs

Error: Message received in processMessage: {"type":"dialogMessageReceived","message":"{\"status\":\"failure\",\"result\":{\"errorCode\":\"user_login_error\",\"errorMessage\":\"User login is required. For silent calls, request must contain either sid or login_hint\",\"name\":\"ClientAuthError\"}}","origin":"https://localhost:4200"
[AddinCode.zip](https://github.com/OfficeDev/Office-Addin-TaskPane-SSO-JS/files/8223033/AddinCode.zip)
}

Tried solutions:
1.Angualr with msal
2.Internet explorer compatibiltiy settings & Trusted sites

Source code attached
We are stuck at this point.
Anybody who can help will be highly appreciated.

**Comment by AlexJerabek** [comment]
Hi @Sachin2-u,

My apologies for the very delayed response. The SSO template has undergone significant revisions since this issue was created. I believe the problem has been fixed by now. If you're still having issues, please let us know.
