### ISSUE TITLE
Error message should include "Outlook" in list of supported Office hosts

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/Office-Addin-TaskPane-SSO-JS#8]
Now that support's been added for Outlook -- in **documentHelper.js**, the message for the exception that’s thrown here should include "Outlook" in the list of supported Office hosts.

![image](https://user-images.githubusercontent.com/3019529/73209894-03551580-40fe-11ea-87e8-1e23b4000884.png)

(Presumably the same adjustment will need made in the corresponding TS repo -- OfficeDev/Office-Addin-TaskPane-SSO.)

**Comment by TCourtneyOwen** [comment]
Ah, good catch!

**Comment by KelBowen** [comment]
@TCourtneyOwen can we resolve this issue?

**Comment by TCourtneyOwen** [comment]
This was just fixed
