### ISSUE TITLE
Help: Separating the frontend and backend (middle-tier)

### ISSUE THREAD

**Issue by McL-M** [OfficeDev/Office-Addin-TaskPane-SSO-JS#88]
Hi! I'm pretty new to add-in development and I'm not sure if this is the right place to post this.

Anyway, after (semi-successfully) building a prototype add-in for Outlook without any authentication, I decided it would be best to implement it and use the most modern method available: SSO.

Spent some time learning how it works and going through the tutorials and docs on Microsoft Learn.

However, I note that the template projects combine the client-side and server-side (middle-tier) code.

In my previous build, I had separated the frontend and backend into different, compartmentalized components.  My assumption was that this would be the best way to keep things clean and easy to work with.

Now, I'm unsure how add-ins are supposed to work.  Is monolithic architecture the norm or should I still be looking to separate my client-side and server-side code?

My initial leaning is still toward the latter.  But I have had some trouble figuring out which components of the template are associated with the client-side and which are needed for the "middle-tier" to work.

Any advice or help for this would be appreciated!

**Comment by davidchesnut** [comment]
Hi @McL-M,

 The templates keep the web server and add-in code in the same project to keep it simple. But you can certainly put them in separate projects. This probably would help with deployment, or if you had more than one web add-in using the same web server.

I'd think of the project structure from this perspective:
- **Add-in project**. This would include anything the manifest file references (HTML, JS, etc...) and any additional files they download to the browser. It's basically the just the add-in parts that run in the browser.
- **Web server project**. This would serve the HTML and JS files for the add-in. Likely just a static web server. It may serve up multiple add-ins.
- **Middle-tier web server project**. For SSO, and scenarios where you have server-side APIs to call from the add-in, this project would include those files. It would handle the OBO flow for SSO, and provide APIs to the web add-in.

You can combine these projects as the template does, or keep them separate. It's up to you and what you need. You also don't have to use webpack. You can configure the web server parts however works best for your scenario.

As I recall the SSO template has a /src/middle-tier folder which would all go into a separate middle-tier project along with the .ENV file if you plan to split this out. You'd need to also configure a webpack config and package.json for it, or use a web server of your choice.

Hope this helps,
David

**Comment by McL-M** [comment]
Thank you, @davidchesnut!  Much appreciate you helping me gain some clarity.

I've already done parts of what you suggest (merging the middle-tier folder files with my server-side project), but was not clear about the .ENV file and webpack config.

I've also had some difficulty sorting which packages are needed on the server-side.  I thought it would be straightforward and that all I'd have to do was look at what packages the .js files needed, but it seems not to be that simple.  (Probably 'cause I'm a noob!🤦‍♂️)

I'll work on it and hopefully figure it out!

The MS Docs are quite extensive but sometimes overwhelming.  It can be a challenge to track down the particular info needed to resolve an issue.  So, again, a human answer is greatly appreciated.

-Micah
