### ISSUE TITLE
documentHelper.js should only contain code for the targeted Office host

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/Office-Addin-TaskPane-SSO-JS#9]
**Issue:** 
Regardless of which Office host is selected during project creation (Excel, Outlook, PowerPoint, or Word), the `./src/helpers/documentHelper.js` file that's created contains code for all four hosts. 

**Suggestion:**
We should update this project template (and the corresponding TS template also) such that the `./src/helpers/documentHelper.js` file that's created only contains code for the Office host that's selected during project creation. e.g., if I create an Excel add-in, that file should only contain code that's relevant to Excel -- and likewise for the other hosts. 

(IMO, not this isn't a high priority issue -- but something we should address when time permits.)

**Comment by TCourtneyOwen** [comment]
Yeah I am not happy about that either and would like to restructure the project when I have time.

**Comment by KelBowen** [comment]
@TCourtneyOwen is it fair to say this is in the backlog?
